type: //rec
rest: //any
required:
  PROJECT_ID: //str
  PROJECT_NAME: //str
  PAT_TYPES:
    type: //any
    of:
    - type: //arr
      contents: //str
    - type: //map
      values: //str
  ALLOW_NO_PAT_TYPE: //bool
  REQUIRE_CHANGE_COMMENTS: //bool
  CYCLE_COUNT: //int
